on:
  pull_request:
    branches:
      - main
name: PR_CI

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'      
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
