on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release-created: ${{ release.outputs.release_created }}
      release-name: ${{ release.outputs.tag_name }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - run: go mod download
      - run: go build -o tfctl    
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: go
          extra-files: |
            README.md
            tfctl
          package-name: release-please-action
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release.outputs.release_created }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
     
      - name: Build AZDO Agent container image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.azdo
          context: .
          tags: |
            ghcr.io/publicis-sapient-anz/tfctl/tfctl-azdo-buster-slim:latest
            ghcr.io/publicis-sapient-anz/tfctl/tfctl-azdo-buster-slim:${{ needs.release.outputs.release-name }}
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      
