apiVersion: tfctl/v1alpha1
kind: Config
metadata:
  name: dev-config
  environment: dev
  description: Dev terraform configuration
spec:
  backend:
    azure:
      autoCreateStorage: true
      storageAccountRg: RD_DEV_AUS
      storageAccountName: stgdevtfstateaus
      storageAccountContainer: dev-infra-state
      stateFileName: dev.tfstate
      subscriptionId: 00000000-0000-0000-0000-000000000000
      tenantId: 00000000-0000-0000-0000-000000000000
      credentials:
        useAzLogin: fallback
        clientIdEnvName: servicePrincipalId
        clientSecretEnvName: servicePrincipalKey
